development:
  adapter: postgresql
  database: xrono_development
  username: rclements
  #host: localhost
  pool: 5
  port: 5432

test:
  adapter: postgresql
  database: xrono_test
  username: rclements
  #host: localhost
  pool: 5
  port: 5432

production:
  adapter: postgresql
  database: xrono_production
  username:
  password:

